package com.personal.godou.ui.theme

import com.personal.godou.data.preferences.AppLanguage

data class AppStrings(
    val appTitle: String,
    val curriculumTitle: String,
    val curriculumSub: String,
    val searchPlaceholder: String,
    val searchResults: String,
    val noResults: String,
    val addVocab: String,
    val editVocab: String,
    val kanjiLabel: String,
    val readingLabel: String,
    val meaningLabel: String,
    val categoryLabel: String,
    val subCategoryLabel: String,
    val studyTagLabel: String,
    val exampleSentenceLabel: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val close: String,
    val mastered: String,
    val learning: String,
    val starredWords: String,
    val starredSub: String,
    val noStarred: String,
    val activeStudyWeek: String,
    val wordsRemain: String,
    val allMastered: String,
    val continueStudy: String,
    val dailyVocabList: String,
    val allCategories: String,
    val settingsTitle: String,
    val themeFlavorTitle: String,
    val darkThemeTitle: String,
    val fontTitle: String,
    val languageTitle: String,
    val privacyTitle: String,
    val privacyOn: String,
    val privacyOff: String
)

val EnglishStrings = AppStrings(
    appTitle = "Godou",
    curriculumTitle = "Weekly Curriculum",
    curriculumSub = "Select a week to begin JLPT N1 study",
    searchPlaceholder = "Search word, reading, or meaning...",
    searchResults = "Search Results",
    noResults = "No matching vocabulary cards found",
    addVocab = "Add Vocab",
    editVocab = "Edit Vocab",
    kanjiLabel = "Kanji Word",
    readingLabel = "Furigana / Reading",
    meaningLabel = "Meaning / Translation",
    categoryLabel = "Category",
    subCategoryLabel = "Sub-Category",
    studyTagLabel = "Study Tag",
    exampleSentenceLabel = "Example Sentence",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    close = "Close",
    mastered = "Mastered",
    learning = "Learning",
    starredWords = "Starred Words",
    starredSub = "Your saved favorite vocabulary cards",
    noStarred = "No starred vocabulary cards yet",
    activeStudyWeek = "ACTIVE STUDY WEEK",
    wordsRemain = "WORDS REMAINING",
    allMastered = "ALL MASTERED!",
    continueStudy = "Continue Study",
    dailyVocabList = "Daily Vocab List",
    allCategories = "All Categories",
    settingsTitle = "Theme & Customization",
    themeFlavorTitle = "M3 Expressive Color Palette",
    darkThemeTitle = "Dark Theme Mode",
    fontTitle = "App Typeface",
    languageTitle = "App Language",
    privacyTitle = "Privacy Protection",
    privacyOn = "PRIVACY: ON",
    privacyOff = "PRIVACY: OFF"
)

val JapaneseStrings = AppStrings(
    appTitle = "吾道 - Godou",
    curriculumTitle = "週別学習カリキュラム",
    curriculumSub = "学習する週を選択してください (JLPT N1)",
    searchPlaceholder = "単語・読み・意味を検索...",
    searchResults = "検索結果",
    noResults = "該当する単語が見つかりません",
    addVocab = "単語追加",
    editVocab = "単語編集",
    kanjiLabel = "漢字表記",
    readingLabel = "読み / ふりがな",
    meaningLabel = "意味・和訳",
    categoryLabel = "カテゴリー",
    subCategoryLabel = "サブカテゴリー",
    studyTagLabel = "学習タグ",
    exampleSentenceLabel = "例文",
    save = "保存",
    cancel = "キャンセル",
    delete = "削除",
    close = "閉じる",
    mastered = "習得済み",
    learning = "学習中",
    starredWords = "スター単語",
    starredSub = "お気に入り登録した単語一覧",
    noStarred = "スター登録された単語はありません",
    activeStudyWeek = "現在の学習週",
    wordsRemain = "単語 残り",
    allMastered = "全単語 習得完了！",
    continueStudy = "学習を始める",
    dailyVocabList = "日別の学習単語",
    allCategories = "すべてのカテゴリー",
    settingsTitle = "テーマ＆カスタマイズ",
    themeFlavorTitle = "M3 Expressive カラーパレット",
    darkThemeTitle = "ダークモード設定",
    fontTitle = "アプリフォント",
    languageTitle = "表示言語",
    privacyTitle = "プライバシー保護",
    privacyOn = "プライバシー: ON",
    privacyOff = "プライバシー: OFF"
)

fun getAppStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.ENGLISH -> EnglishStrings
        AppLanguage.JAPANESE -> JapaneseStrings
    }
}
